// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc2175.N00bM0d3Trap;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainLeftSpeedController;
    public static SpeedController drivetrainRightSpeedController;
    public static RobotDrive drivetrainRobotDrive;
    public static SpeedController shooterWheels;
    public static Solenoid shooterPlunger;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainLeftSpeedController = new Talon(1, 1);
	LiveWindow.addActuator("Drivetrain", "Left Speed Controller", (Talon) drivetrainLeftSpeedController);
        
        drivetrainRightSpeedController = new Talon(1, 2);
	LiveWindow.addActuator("Drivetrain", "Right Speed Controller", (Talon) drivetrainRightSpeedController);
        
        drivetrainRobotDrive = new RobotDrive(drivetrainLeftSpeedController, drivetrainRightSpeedController);
	
        drivetrainRobotDrive.setSafetyEnabled(true);
        drivetrainRobotDrive.setExpiration(0.1);
        drivetrainRobotDrive.setSensitivity(0.5);
        drivetrainRobotDrive.setMaxOutput(1.0);
        
        shooterWheels = new Talon(1, 3);
	LiveWindow.addActuator("Shooter", "Wheels", (Talon) shooterWheels);
        
        shooterPlunger = new Solenoid(1, 1);
	LiveWindow.addActuator("Shooter", "Plunger", shooterPlunger);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
